### ISSUE TITLE
请问你做完题之后，Google联系你了吗？

### ISSUE THREAD

**Issue by jollerw** [liuyubobobo/My-Google-Foobar#1]

**Comment by liuyubobobo** [comment]
我很早之前因为别的原因被 google 的 hr 联系过，所以我觉得我在 google foobar 上的经历不能说明问题。但大概率现在这个活动已经过期了，所有 google foobar 问题的答案和解析已经满天飞了，显然 google foobar 也已经不更新了。

如果关注 google 的招聘，kickstart 或者 codejam 应该是更好的去处。
